version: "3"

services:
  consul-server:
    image: consul:latest
    command: "consul agent -config-file=/etc/consul.d/config.json"
    volumes:
      - ./consul/server.d/:/etc/consul.d/

  nomad-server:
    build: ./nomad
    privileged: true
    expose:
      - "4646"
      - "4647"
      - "4648"
    ports:
      - "4646:4646"
    volumes:
      - ./nomad/server.d/:/etc/nomad.d/
      - ./consul/client.d/:/etc/consul.d/
    depends_on:
      - consul-server

  # just need follower to avoid port 4646 conflict
  nomad-server-follower:
    build: ./nomad
    privileged: true
    expose:
      - "4647"
      - "4648"
    volumes:
      - ./nomad/server.d/:/etc/nomad.d/
      - ./consul/client.d/:/etc/consul.d/
    depends_on:
      - nomad-server

  nomad-client-dc1:
    build: ./nomad
    privileged: true
    volumes:
      - ./nomad/client-dc1.d/:/etc/nomad.d/
      - ./consul/client.d/:/etc/consul.d/
    depends_on:
      - nomad-server

  nomad-client-dc2:
    build: ./nomad
    privileged: true
    volumes:
      - ./nomad/client-dc2.d/:/etc/nomad.d/
      - ./consul/client.d/:/etc/consul.d/
    depends_on:
      - nomad-server
